### ISSUE TITLE
Submit at packagist.org

### ISSUE THREAD

**Issue by KuLi** [hosting-de-labs/hostingde-api-php#2]
Please submit this repo at packagist.org for better composer integration.

**Comment by KuLi** [comment]
Can I make a pull request for the complete Composer integration?

**Comment by michaelernst** [comment]
Hi Felix,

sorry for the late response, we must have missed your initial request. 

Sure, if you create a PR we will support it.

Best
Michael

**Comment by KuLi** [comment]
Da ihr aus Deutschland seid, können wir sicher auch auf deutsch weiter machen.

Wie sieht es dabei mit Breacking Changes aus? Durch die Änderung würde ich zb die Ordner groß schreiben für das Autoloading vom Composer. Alles unterhalb von "classes" würde auch in einem anderen Namespace fallen. zb. classes/account/AccountUser.php würde dann **C**lasses/**A**ccount/AccountUser.php im Namespace Hostingde\API\Classes\Account sein.

**Comment by michaelernst** [comment]
Ich geb das mal an @membero ab, da er das bei uns intern betreut.

**Comment by membero** [comment]
Hallo KuLi,

wird das groß Schreiben von Composer benötigt? Wenn ja, würde ich einen PR akzeptieren. Es ist sinnvoll, Standards zu folgen und Composer kann man im PHP Bereich ja als Standard sehen ;)
